### Methods to make an array

In [46]:
import numpy as np
z = np.zeros(11,dtype=np.int16)               #add this parameter to make elements of specific data type
k = np.ones(5)
l = np.linspace(2,10,5)                       #creates a array of 5 elements having range from 2 to 10
o = np.arange(1,20,2)                         #creates a array of n elements having range from 1 to 20 with increment of 2
m = np.array([10,20,30,40])
n = np.random.randint(200,size=6)             #creates a random array of size 6 having range till 200
print(z , k , l , o , m , n)


[0 0 0 0 0 0 0 0 0 0 0] [1. 1. 1. 1. 1.] [ 2.  4.  6.  8. 10.] [ 1  3  5  7  9 11 13 15 17 19] [10 20 30 40] [  4 170 148  44 167 133]


### Shapes & Size

In [35]:
o.shape

(10,)

In [37]:
o.reshape(2,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [38]:
o.size                                        #to check total noumber of elements

10

In [40]:
o.dtype                                       #data type of array elements

dtype('int32')

In [42]:
o.itemsize                                    #size of array elements

4

### operation on elements of array

In [43]:
m < 30

array([ True,  True, False, False])

In [45]:
m = m*20                                                                         #loops around all the elements
m

array([ 4000,  8000, 12000, 16000])

In [47]:
m = m/20
m

array([0.5, 1. , 1.5, 2. ])

In [50]:
print(o.sum(), o.min(), o.max(), o.mean() ,o.var() ,o.std())                   #use parameter axis=1 to perform operation row wise only


100 1 19 10.0 33.0 5.744562646538029


### Micellaneous

In [63]:
a  = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
np.random.shuffle(a)                                         #randomly orient a array
a

array([8, 3, 0, 9, 4, 2, 7, 6, 1, 5])

In [66]:
np.random.choice(a)                                          #randomly choses a no from given array

5

In [70]:
a = np.where(a > 5, 0, 1)                                    #where a is > 5 replace those elements with 0 and rest with 1
a

array([0, 1, 1, 0, 1, 1, 0, 0, 1, 1])

### Transpose of matrix and Dot product

In [72]:
c = np.array([1,2,3,4,5,6])
b = np.array([11,12,13,14,15,16])
c @ b                                                        # @ sign represents dot product

301

In [78]:
c = c.reshape(2,3)
c

array([[1, 2, 3],
       [4, 5, 6]])

In [79]:
c.T                                                         # T sign is used to represtent transposeof a matrix

array([[1, 4],
       [2, 5],
       [3, 6]])